import { db } from '../firebaseConfig';
import { collection, addDoc, getDocs, deleteDoc, updateDoc, doc, setDoc, getDoc } from 'firebase/firestore';
import { StudentProfile, OfficialStudent } from '../types';

const COLLECTION_NAME = 'students';
const SETTINGS_COLLECTION = 'settings';
const ROSTER_DOC_ID = 'class_roster';

/**
 * CRITICAL HELPER: 
 * Firestore throws an error if any field is 'undefined'.
 * This function recursively converts 'undefined' to 'null'.
 */
const sanitizeData = (data: any): any => {
  if (data === undefined) return null;
  if (data === null) return null;
  
  if (Array.isArray(data)) {
    return data.map(sanitizeData);
  }
  
  if (typeof data === 'object') {
    const newObj: any = {};
    for (const key in data) {
      newObj[key] = sanitizeData(data[key]);
    }
    return newObj;
  }
  
  return data;
};

/**
 * Save a student's result to Firebase Cloud Firestore
 */
export const saveStudentResult = async (profile: StudentProfile): Promise<void> => {
  if (!db) {
    console.error("Database not initialized");
    return; // Fail gracefully
  }
  try {
    const colRef = collection(db, COLLECTION_NAME);
    // Remove ID (auto-generated by Firestore usually, or keep consistent)
    const { id, ...dataToSave } = profile; 
    
    // SANITIZE DATA BEFORE SAVING
    const cleanData = sanitizeData(dataToSave);

    await addDoc(colRef, {
        ...cleanData,
        createdAt: new Date().toISOString()
    });
    console.log("Document written successfully");
  } catch (e: any) {
    console.error("Error adding document: ", e);
    if (e.code === 'permission-denied') {
        throw new Error("權限不足：請檢查 Firebase Rules 設定");
    }
    throw e;
  }
};

/**
 * Fetch all students for the Teacher Dashboard
 */
export const fetchClassroomData = async (): Promise<StudentProfile[]> => {
  if (!db) {
      throw new Error("資料庫未連接");
  }
  try {
    const colRef = collection(db, COLLECTION_NAME);
    const snapshot = await getDocs(colRef);
    
    if (snapshot.empty) {
        return [];
    }

    const students: StudentProfile[] = [];
    
    snapshot.forEach((doc) => {
      const data = doc.data() as Omit<StudentProfile, 'id'>;
      // Basic validation
      if (data.name && data.animalType) {
          students.push({ id: doc.id, ...data });
      }
    });
    
    return students;
  } catch (e: any) {
    console.error("Error fetching documents: ", e);
    if (e.code === 'permission-denied') {
        throw new Error("權限不足：請至 Firebase Console > Firestore > Rules 開啟讀取權限");
    }
    if (e.code === 'unimplemented' || e.message.includes('Cloud Firestore API has not been used')) {
        throw new Error("API 未啟用：請至 Google Cloud Console 啟用 Firestore API");
    }
    throw new Error("無法讀取雲端資料，請檢查網路");
  }
};

/**
 * Save the Official Roster to Cloud (Syncs across devices)
 */
export const saveOfficialRoster = async (roster: OfficialStudent[]): Promise<void> => {
    if (!db) return;
    try {
        const docRef = doc(db, SETTINGS_COLLECTION, ROSTER_DOC_ID);
        const cleanRoster = sanitizeData(roster);
        // Overwrite the existing roster
        await setDoc(docRef, { 
            students: cleanRoster,
            updatedAt: new Date().toISOString()
        });
        console.log("Roster synced to cloud");
    } catch (e) {
        console.error("Error saving roster:", e);
        throw new Error("名單上傳雲端失敗");
    }
};

/**
 * Fetch the Official Roster from Cloud
 */
export const fetchOfficialRoster = async (): Promise<OfficialStudent[]> => {
    if (!db) return [];
    try {
        const docRef = doc(db, SETTINGS_COLLECTION, ROSTER_DOC_ID);
        const docSnap = await getDoc(docRef);
        
        if (docSnap.exists()) {
            const data = docSnap.data();
            return data.students as OfficialStudent[] || [];
        } else {
            return [];
        }
    } catch (e) {
        console.error("Error fetching roster:", e);
        return [];
    }
};


/**
 * Delete a single student by ID
 */
export const deleteStudent = async (id: string): Promise<void> => {
  if (!db) return;
  try {
    await deleteDoc(doc(db, COLLECTION_NAME, id));
  } catch (error) {
    console.error("Error deleting document:", error);
    throw error;
  }
};

/**
 * Update a student's name (Fix typos)
 */
export const updateStudentName = async (id: string, newName: string): Promise<void> => {
  if (!db) return;
  try {
    await updateDoc(doc(db, COLLECTION_NAME, id), { name: newName });
  } catch (error) {
    console.error("Error updating name:", error);
    throw error;
  }
};

/**
 * Update a student's gender (Fix missing/wrong gender)
 */
export const updateStudentGender = async (id: string, newGender: string): Promise<void> => {
  if (!db) return;
  try {
    await updateDoc(doc(db, COLLECTION_NAME, id), { gender: newGender });
  } catch (error) {
    console.error("Error updating gender:", error);
    throw error;
  }
};

/**
 * Clear all data (Dangerous!)
 */
export const clearDatabase = async (): Promise<void> => {
    if (!db) return;
    const colRef = collection(db, COLLECTION_NAME);
    const snapshot = await getDocs(colRef);
    const deletePromises = snapshot.docs.map(d => deleteDoc(doc(db, COLLECTION_NAME, d.id)));
    await Promise.all(deletePromises);
};